libIME/CandidateWindow.cpp
libIME/CandidateWindow.h

I've scanned the project with [cppcheck](http://cppcheck.sourceforge.net/) and done some cleanups. Please take a look.

Minor cleanups

---

.github/workflows/nightly.yml
CMakeLists.txt
ChewingTextService/CMakeLists.txt

Nightly build is published to https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly

Setup Nightly pre-release

---

ChewingTextService/ChewingTextService.cpp
installer/installer.nsi

Only those are visible to the user are changed.

Use https URL

---

ChewingPreferences/ChewingPreferences.exe.manifest

* Apply indentation
* Declare compatibility with Windows versions
* Fill in correct info in manifest

Manifest improvements

---

ChewingTextService/ChewingTextService.cpp

feat: use chewing_ack

---

ChewingTextService/ChewingTextService.cpp
libIME/TextService.cpp

feat: show chi/eng mode toast after manual toggle

---

libIME/DisplayAttributeInfo.h
libIME/ImeModule.cpp

Fixes #179
Fixes #145 
Fixes #101 
Fixes #66

fix: only use GetSysColor color index

---

ChewingTextService/ChewingTextService.cpp
ChewingTextService/ChewingTextService.h
libIME/TextService.cpp

fix: end composition and hide windows on blur

---

ChewingTextService/ChewingTextService.cpp

feat: show chi/eng mode toast after toggle capslock

---

ChewingTextService/ChewingConfig.cpp
ChewingTextService/ChewingConfig.h
ChewingTextService/ChewingTextService.cpp
libIME/TextService.h

feat: listen to registry change event

---

Cargo.lock
chewing_tip/Cargo.toml
chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/lang_bar.rs
chewing_tip/src/ts/menu.rs

feat: use zhconv for conversion

---

Cargo.lock
installer/windows-chewing-tsf.wxs
tsfreg/Cargo.toml
tsfreg/src/main.rs

Thanks to the information from mozc and keyman:
* https://github.com/google/mozc/issues/736
* https://github.com/keymanapp/keyman/wiki/Making-sense-of-the-Windows-Layout-Registration#installlayoutortip-win32-api

feat: enable ChewingTIP by default

---

Cargo.lock
chewing_tip/Cargo.toml
chewing_tip/build.rs
chewing_tip/rc/ChewingTextService.manifest
chewing_tip/src/gfx.rs
chewing_tip/src/window/candidate_window.rs
chewing_tip/src/window/message_window.rs

refactor: improve HiDPI handling

---

chewing_tip/src/gfx.rs
chewing_tip/src/window/candidate_window.rs
chewing_tip/src/window/message_window.rs

fix: use GetDpiForMonitor to detect monitor DPI

---

chewing_tip/src/window/candidate_window.rs
preferences/src/config.rs

fix: ensure to resize empty candidate window correctly

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/key_event.rs

fix: better handling of capslock state

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/config.rs
preferences/src/config.rs
preferences/ui/config-window.slint

feat: make phrase-choice-rearward configurable

---

Cargo.lock
chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/config.rs
chewing_tip/src/window/candidate_window.rs
chewing_tip/src/window/message_window.rs
preferences/Cargo.toml
preferences/src/config.rs
preferences/src/fonts.rs
preferences/src/main.rs
preferences/ui/config-window.slint

feat: make font configurable

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/config.rs
chewing_tip/src/window/candidate_window.rs
chewing_tip/src/window/message_window.rs
preferences/src/config.rs
preferences/ui/config-window.slint

feat: make font color configurable

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/config.rs
chewing_tip/src/ts/ui_elements/candidate_list.rs
preferences/src/config.rs
preferences/ui/config-window.slint

feat: make notification configurable

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/edit_session.rs
chewing_tip/src/ts/mod.rs

fix: allow invalid HWND for UILess console

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/mod.rs
chewing_tip/src/ts/theme.rs

refactor: try to improve dark mode detection

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

ci: adjust how we draft nightly release

---

preferences/src/fonts.rs

feat: display localized font names in preferences

---

preferences/Cargo.toml
preferences/src/fonts.rs

fix: use GDI to enumerate localized font names correctly

---

chewing_tip/src/gfx.rs
chewing_tip/src/ts/ui_elements/candidate_list.rs
chewing_tip/src/ts/ui_elements/notification.rs

fix: get DWrite font names from GDI font names

---

Cargo.lock
chewing_tip/src/ts/chewing.rs
preferences/src/config.rs
preferences/ui/config-window.slint

feat: enable using Shift for easy symbol input

---

Cargo.lock
editor/Cargo.toml
editor/src/editor.rs
editor/src/main.rs
editor/ui/bopomofo-keyboard.slint
editor/ui/editor-window.slint
editor/ui/index.slint

feat: support sorting and filtering in dictionary editor

---

Cargo.lock
chewing_tip/Cargo.toml
chewing_tip/src/ts/chewing.rs

fix: always load inputmode lang bar button

---

chewing_tip/src/ts/chewing.rs

feat: only toggle lang mode when short press Shift

---

chewing_tip/src/ts/chewing.rs

fix: correctly handle all Simplified Chinese conversion condition

---

chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/key_event.rs

fix: ignore keys with ctrl or alt modifiers

---

Cargo.lock
chewing_tip/Cargo.toml
chewing_tip/src/ts/ui_elements/candidate_list.rs
chewing_tip/src/ts/ui_elements/notification.rs
editor/Cargo.toml
preferences/Cargo.toml
tsfreg/Cargo.toml

fix: preserve precision when converting window coordinates

---

chewing_tip/src/gfx.rs
chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/ui_elements/candidate_list.rs
chewing_tip/src/ts/ui_elements/notification.rs
chewing_tip/src/window.rs

fix: retrieve DPI after window is moved and apply DPI scaling to font size

---

Cargo.lock
preferences/Cargo.toml
preferences/src/config.rs
preferences/src/fonts.rs
preferences/src/main.rs

fix: grant app container access to registry

---

editor/ui/editor-window.slint

refactor: update label for frequency in editor

---

Cargo.lock
editor/Cargo.toml
editor/src/main.rs
preferences/Cargo.toml
preferences/src/main.rs

fix: menubar is no longer semi-transparent

---

chewing_tip/Cargo.toml
chewing_tip/src/ts/chewing.rs
installer/windows-chewing-tsf.wxs
preferences/src/main.rs

fix: make config launcher compatiable with sandboxed applications

---

preferences/src/config.rs
preferences/src/fonts.rs
preferences/ui/config-window.slint

feat: add apply button to preferences

---

editor/ui/about-window.slint
editor/ui/editor-window.slint
preferences/ui/about-window.slint
preferences/ui/config-window.slint

refactor: set default-font-family for all slint window

---

chewing_tip/src/ts/config.rs

fix: correctly parse 000000FF to RRGGBBAA

---

CHANGELOG.md
chewing_tip/src/ts/chewing.rs

fix: make space key available as shortcut when not composing

---

CHANGELOG.md
chewing_tip/src/ts/chewing.rs

fix: lower shift-key hold_duration threshold to 200 miliseconds

---

CHANGELOG.md
Cargo.lock
Cargo.toml

chore(deps): update libchewing

---

CHANGELOG.md
chewing_tip/src/ts/chewing.rs
chewing_tip/src/ts/mod.rs

fix: correctly detect focus change and resync Caps Lock state

---

CHANGELOG.md
chewing_tip/src/ts/chewing.rs

fix: register Caps Lock keyup even when other keys were held

---

CHANGELOG.md
Cargo.lock
editor/Cargo.toml
editor/src/editor.rs
editor/ui/editor-window.slint
xtask/src/installer.rs

feat: support import / export user dictionary as CSV file

---

CHANGELOG.md
tip/src/ts/chewing.rs
tip/src/ts/key_event.rs

feat: handle Numpad keys as digits when NumLock is toggled

---

CHANGELOG.md
tip/src/ts/chewing.rs

fix: keep input modes when focus changes

---

Cargo.lock
preferences/package-lock.json
preferences/package.json
preferences/src-tauri/Cargo.lock
preferences/src/App.tsx

fix: config handling and UI widget handling
